//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venkat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeEntitie : DbContext
    {
        public EmployeeEntitie()
            : base("name=EmployeeEntitie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employe> tblEmploye { get; set; }
        public virtual DbSet<Department> tblDepartment { get; set; }

        public System.Data.Entity.DbSet<Venkat.Models.EmployeeByDepartment> EmployeeByDepartments { get; set; }
    }
}
