//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venkat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public int IdEmployee { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public int DepartmentId { get; set; }
        public string UrlImage { get; set; }
        public string AltImage { get; set; }
    
        public virtual Department tblDepartment { get; set; }
    }
}
